Repository masa-finance/masa-bittensor, pull requests merged in 2024-07, with the labels that each got.

#127 feat: add health check endpoint and fix out of bounds issue
  masa/base/validator.py
  neurons/miner.py
Labels: bug, feature

#131 ci(release): add release configuration
  .github/release.yml
Labels: ci

#134 ci: add commitlint workflow
  .github/workflows/commitlint.yml
Labels: ci

#136 Fix endpoints
  .github/workflows/commitlint.yml
  masa/api/validator_api.py
  masa/validator/discord/all_guilds/parser.py
  masa/validator/discord/channel_messages/parser.py
  masa/validator/discord/channel_messages/reward.py
  masa/validator/discord/guild_channels/parser.py
  masa/validator/discord/guild_channels/reward.py
  masa/validator/discord/user_guilds/parser.py
  masa/validator/forwarder.py
Labels: bug

#112 feat: implement basic sanitation for miner selection
  masa/utils/uids.py
  masa/validator/forwarder.py
  tests/test_template_validator.py
Labels: enhancement

#116 fix/tempo fetching
  masa/base/miner.py
  neurons/miner.py
Labels: bug

#138 feat: playground server and improvements
  Makefile
  healthcheck-dockerfile
  healthcheck/main.py
  masa/__init__.py
  masa/api/validator_api.py
  masa/base/healthcheck.py
  masa/base/validator.py
  masa/validator/forwarder.py
  neurons/miner.py
Labels: enhancement

#114 Adding deepnote simulation notebook to repo
  notebooks/bittensor_rewards_simulation/Rewards Simulation.ipynb
Labels: enhancement
